version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: krisz-appstore-mqtt-exporter_mqtt-exporter_1
      APP_PORT: 9000

  mqtt-exporter:
    image: kpetrem/mqtt-exporter
    ports:
      - "9000:9000"
    environment:
      - MQTT_ADDRESS=192.168.88.223
      - MQTT_TOPIC=#
    restart: unless-stopped
