version: "3.7"

services:
  mqtt-exporter:
    image: kpetrem/mqtt-exporter
    ports:
      - 9000:9000
    environment:
      - MQTT_ADDRESS=${APP_SETTING_MQTT_HOST}
      - MQTT_TOPIC=${APP_SETTING_MQTT_TOPIC}
    restart: unless-stopped
